fx_version 'cerulean'
game 'gta5'
lua54 'yes'

author 'Legacy_DMC'
description 'Discord: https://discord.gg/KsvJWyvpZU'
version 'Release-Build-30.06.2026'

shared_script 'config/vehicleData.lua'
shared_script 'config/tireData.lua'
shared_script 'config/hudData.lua'
shared_script 'config/cameraData.lua'
shared_script 'config/physicsData.lua'
shared_script 'config/performanceIndexData.lua'
shared_script 'config/engineData.lua'
shared_script 'config/antilagProfiles.lua'
shared_script 'config/gearShiftProfiles.lua'
shared_script 'config/allowList.lua'

shared_script 'engine/network/exports/exports.lua'
server_script 'engine/network/server/server.lua'
server_script 'engine/network/server/server_events.lua'
server_script 'engine/network/server/server_vars.lua'

client_script 'engine/base/varinit.lua'
client_script 'engine/common/binds.lua'
client_script 'engine/common/binds_functions.lua'
client_script 'engine/threads/brake/brake.lua'
client_script 'engine/threads/brake/brake_functions.lua'
client_script 'engine/threads/caller/caller.lua'
client_script 'engine/threads/caller/caller_functions.lua'
client_script 'engine/threads/camera/camera.lua'
client_script 'engine/threads/camera/camera_functions.lua'
client_script 'engine/threads/chassis/chassis.lua'
client_script 'engine/threads/chassis/chassis_functions.lua'
client_script 'engine/threads/differential/differential.lua'
client_script 'engine/threads/differential/differential_functions.lua'
client_script 'engine/threads/drivetrain/drivetrain.lua'
client_script 'engine/threads/drivetrain/drivetrain_functions.lua'
client_script 'engine/threads/ecu/ecu.lua'
client_script 'engine/threads/ecu/ecu_functions.lua'
client_script 'engine/threads/engineTorque/engineTorque.lua'
client_script 'engine/threads/engineTorque/engineTorque_functions.lua'
client_script 'engine/threads/flywheel/flywheel.lua'
client_script 'engine/threads/flywheel/flywheel_functions.lua'
client_script 'engine/threads/gamePad/gamePad.lua'
client_script 'engine/threads/gamePad/gamePad_functions.lua'
client_script 'engine/threads/hud/hud.lua'
client_script 'engine/threads/hud/hud_functions.lua'
client_script 'engine/threads/nitrous/nitrous.lua'
client_script 'engine/threads/nitrous/nitrous_functions.lua'
client_script 'engine/threads/performanceIndex/performanceIndex.lua'
client_script 'engine/threads/performanceIndex/performanceIndex_functions.lua'
client_script 'engine/threads/steering/steering.lua'
client_script 'engine/threads/steering/steering_functions.lua'
client_script 'engine/threads/transmission/transmission.lua'
client_script 'engine/threads/transmission/transmission_functions.lua'
client_script 'engine/threads/tuning/tuning.lua'
client_script 'engine/threads/tuning/tuning_functions.lua'
client_script 'engine/threads/tyre/tyre.lua'
client_script 'engine/threads/tyre/tyre_functions.lua'
client_script 'engine/threads/antilag/antilag.lua'
client_script 'engine/threads/antilag/antilag_functions.lua'
client_script 'engine/base/cbe.lua'
client_script 'engine/network/netSync/sync.lua'
client_script 'engine/debug/time/time.lua'
client_script 'engine/debug/time/time_functions.lua'
client_script 'engine/debug/forceFeedBack/ffb.lua'
client_script 'engine/debug/forceFeedBack/ffb_functions.lua'
client_script 'engine/network/netSync/threadSync.lua'

ui_page 'ui/index.html'

files {
    'ui/index.html',
    'ui/styles/style.css',
    'ui/scripts/script.js',
    "audio/**/*.awc",
    "audio/**/*.dat54.rel",
}

data_file 'AUDIO_WAVEPACK'  'audio/core/dynamic_soundbank'
data_file 'AUDIO_SOUNDDATA' 'audio/core/dynamic_soundbank.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/core/antilag_soundbanks.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/core/gearshift_soundbanks.dat'
